Pass parent_type to supported reducers
ianlini/flatten-dict pull request #55
Opened 2021-12-29 18:45 UTC by omerfarukdogan

I have a requirement to flatten lists with list syntax (square brackets). For example,

```
{
  "a": ["b", "c"],
  "d": ["e", "f", g"]
}
```

should be flattened as:

```
{
  "a[0]": "b",
  "a[1]": "c",
  "d[0]": "e",
  "d[1]": "f",
  "d[2]": "g"
}
```

Currently, lists are reduced same as dictionaries and I think it is unhealthy because it's not clear if a number is a key of a dictionary or index of a list. For example, `flatten({ "a": ["x", "y"] }, enumerate_types=(list,))` and `flatten({ "a": { 0: "x", 1: "y" } })` has the same result.

With this change, reducers will be able to have three parameters, and if they do, parent type will be passed as the third parameter. Therefore, reducers can check this and decide how to flatten different kinds of objects.

2021-12-30 16:52 UTC, ianlini commented
Thanks for your contribution. The idea is good, but I think it would be more general to use `_d` instead of `type(_d)`, and use `isinstance()` instead of `issubclass()`. Could you make the change? BTW, you have to run `black .` to format the code so that you can pass the flake8 check.

2021-12-30 16:55 UTC, ianlini commented on src/flatten_dict/tests/flatten_dict_test.py
> +            return f"{parent}[{key}]"
We are still supporting Python 2.7, so you cannot use the f-string.

2021-12-31 07:38 UTC, ianlini commented on src/flatten_dict/flatten_dict.py
> +    reducer_accepts_parent_obj = len(inspect.signature(reducer).parameters) == 3
python 2.7 doesn't have `inspect.signature`, so you need to use (funcsigs)[https://funcsigs.readthedocs.io/en/0.4/]. You can refer to how I did for `pathlib`. I know it's annoying. If you don't want to dig into the poetry config. You can try-catch this line and give `reducer_accepts_parent_obj` a default value `False`, and I will refactor this to support python 2.7 later.

2021-12-31 07:42 UTC, ianlini requested changes

2021-12-31 07:42 UTC, ianlini commented on src/flatten_dict/flatten_dict.py
> +    reducer_accepts_parent_obj = len(inspect.signature(reducer).parameters) == 3
Oh, but the test will fail if you do so. You can use (pytest.mark.skipif)[https://docs.pytest.org/en/latest/how-to/skipping.html#id1]

2022-01-03 07:15 UTC, omerfarukdogan commented
Thanks, I have modified the pull request according to your feedback. Is it possible that you merge it and release a new version?

2022-01-04 15:51 UTC, merged

2022-01-04 15:54 UTC, ianlini commented
I will release a new version after merging another PR. For now, you can use the master branch.